driverClassName=org.mariadb.jdbc.Driver
jdbcUrl=%{system:todos.db-mariadb.url}
dataSource.user=%{system:todos.db-mariadb.username}
dataSource.password=%{system:todos.db-mariadb.password}
maximumPoolSize=10