driverClassName=org.postgresql.Driver
jdbcUrl=%{system:aspectow-console.db-supabase.url}
dataSource.user=%{system:aspectow-console.db-supabase.username}
dataSource.password=%{system:aspectow-console.db-supabase.password}
maximumPoolSize=10