driverClassName=com.mysql.cj.jdbc.Driver
jdbcUrl=%{system:todos.db-mysql.url}
dataSource.user=%{system:todos.db-mysql.username}
dataSource.password=%{system:todos.db-mysql.password}
maximumPoolSize=10